issues:
  exclude-use-default: false
linters:
  disable-all: true
  enable:
    - revive
linters-settings:
  revive:
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: exported
        disabled: true
      - name: line-length-limit
        arguments: [120]
      - name: package-comments
        disabled: true
